//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariHesapOtomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int satisID { get; set; }
        public int urunID { get; set; }
        public System.DateTime satisTarihi { get; set; }
        public int musteriID { get; set; }
        public int urunAdet { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
